name: Build and deploy WAR app to Azure Web App - teamtaskmanagerethara

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: backend/taskmanager
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          # The path must reflect where the WAR file is actually generated
          path: 'backend/taskmanager/target/*.war'

  deploy:
    runs-on: ubuntu-latest
    needs: build 
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'teamtaskmanagerethara'
          slot-name: 'Production'
          # After downloading the artifact, the .war file will be in the root of the runner
          package: '*.war'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_94EE79DB3FC64DF6BFC480DD9F33BF3D }}
